import {
  Atom,
  Boxes,
  Braces,
  CircleDot,
  Cloud,
  Code2,
  Coffee,
  Container,
  Database,
  FileCode2,
  GitBranch,
  Github,
  Globe,
  KeyRound,
  Layers,
  Leaf,
  Palette,
  Radio,
  Server,
  Terminal,
  Triangle,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  javascript: Braces,
  typescript: FileCode2,
  python: Code2,
  java: Coffee,
  "c / c++": Terminal,
  html: Globe,
  css: Palette,
  react: Atom,
  "react 19": Atom,
  "next.js": Triangle,
  "tailwind css": Wind,
  "node.js": Server,
  "express.js": Server,
  express: Server,
  fastapi: Zap,
  postgresql: Database,
  mongodb: Leaf,
  qdrant: Layers,
  neon: Database,
  sqlalchemy: Database,
  git: GitBranch,
  github: Github,
  docker: Container,
  vercel: Triangle,
  render: Cloud,
  cloudinary: Cloud,
  "vs code": Code2,
  "rest apis": Waves,
  jwt: KeyRound,
  "server-sent events": Radio,
  "stripe api": CircleDot,
  "socket.io": Radio,
};

export function techIcon(name: string): LucideIcon {
  return map[name.trim().toLowerCase()] ?? Boxes;
}